CREATE PROCEDURE TRANSFERENCE_DELETE
@ID SMALLINT,
@PROC_RESULT TINYINT OUTPUT
AS
BEGIN TRY
	BEGIN
		DELETE FROM TB_TRANSFERENCE
		WHERE ID = @ID;
		SET @PROC_RESULT = 3;
	END
END TRY
BEGIN CATCH
	SET @PROC_RESULT = 0;
END CATCH
GO