CREATE VIEW VW_TRANSFERENCES AS
SELECT 
	T.ID AS TRANSFERENCE, 
	T.DATE,
	T.AMOUNT,
	T.SOURCE,
	T.DETAILS,
	T.CREATION_DATE,
	T.UPDATE_DATE,
	K.ID AS KIND,
	K.NAME
FROM TB_TRANSFERENCE T
INNER JOIN TB_TRANSFERENCE_KIND K ON K.ID = T.KIND;