ALTER PROCEDURE SOURCE_SAVE
@ID SMALLINT,
@DESCRIPTION VARCHAR(50),
@PROC_RESULT VARCHAR(300) OUTPUT
AS
BEGIN TRY
	IF  @ID = 0
		BEGIN
			INSERT INTO TB_SOURCE (
			[DESCRIPTION]
			) VALUES (
			@DESCRIPTION
			)
			SET @PROC_RESULT = 'SUCCESS ON INSERT';
		END
	ELSE
		BEGIN
			UPDATE TB_SOURCE SET
			[DESCRIPTION] = @DESCRIPTION
			WHERE ID = @ID;
			SET @PROC_RESULT = 'SUCCESS ON UPDATE';
		END
END TRY
BEGIN CATCH
	SET @PROC_RESULT = ERROR_MESSAGE();
END CATCH
GO

